---
title: "IBD HVI modules 64 traits S-LDSC"
author: "Kushal K. Dey, Karthik Jagadeesh and Alkes Price"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(corrplot)
library(qvalue)
```

## Gene Modules for HVI

```{r}
ll = list.files("/Users/kushaldey/Documents/singlecellLDSC/data/Healthy_gene_score_Feb1/")
ll
```

## Size of gene modules

```{r}
cc= c()
for(mm in 1:length(ll)){
  df1 = read.delim(paste0("/Users/kushaldey/Documents/singlecellLDSC/data/Healthy_gene_score_Feb1/", ll[mm]), header=F)
  df2 = read.delim(paste0("/Users/kushaldey/Documents/singlecellLDSC/data/HealthyVInflamed_gene_score_Feb1/", ll[mm]), header=F)
  cc = rbind(cc, c(mean(df1[,2]), mean(df2[,2])))
}
colnames(cc) = c("Healthy", "HVI")
head(cc)
```

## Load data

```{r}
IBD_ldsc = get(load("/Users/kushaldey/Documents/singlecellLDSC/output/HVI_gene_score_Feb1_plus_Healthy_plus_All.rda"))
dim(IBD_ldsc)
```

## tau-star

### Roadmap Enhancers linked to Genes 

```{r}
tau_table = IBD_ldsc[,,3,1]
ptau_table = IBD_ldsc[,,3,2]
qtau_table = matrix(qvalue(as.vector(ptau_table))$qvalues, nrow = nrow(tau_table), ncol = ncol(tau_table))
ptau_table2 = matrix(qvalue(as.vector(ptau_table))$pvalues, nrow = nrow(tau_table), ncol = ncol(tau_table))
tau_table[which(qtau_table > 0.1)] = 0
```

```{r fig.height=12, fig.width=20}
corrplot(tau_table, is.corr = F, tl.cex = 0.7, tl.srt = 45)
```

### 100kb linked to Genes 

```{r}
tau_table = IBD_ldsc[,,1,1]
ptau_table = IBD_ldsc[,,1,2]
qtau_table = matrix(qvalue(as.vector(ptau_table))$qvalues, nrow = nrow(tau_table), ncol = ncol(tau_table))
ptau_table2 = matrix(qvalue(as.vector(ptau_table))$pvalues, nrow = nrow(tau_table), ncol = ncol(tau_table))
tau_table[which(qtau_table > 0.1)] = 0
```

```{r fig.height=12, fig.width=20}
corrplot(tau_table, is.corr = F, tl.cex = 0.7, tl.srt = 45)
```

```{r}
apply(tau_table, 2, mean)[order(apply(tau_table, 2, mean), decreasing = T)][1:10]
```


## Enrichment 

### Roadmap Enhancer

```{r}
E_table = IBD_ldsc[,,3,3]
pE_table = IBD_ldsc[,,3,4]
qE_table = matrix(qvalue(as.vector(pE_table))$qvalues, nrow = nrow(E_table), ncol = ncol(E_table))
pE_table2 = matrix(qvalue(as.vector(pE_table))$pvalues, nrow = nrow(E_table), ncol = ncol(E_table))
E_table[which(qE_table > 0.01 & pE_table2 > 0.001)] = 1 
E_table[E_table < 1.1] = 1
Edif_table = E_table - mean(E_table)
Edif_table[Edif_table < 0] = 0
```

```{r fig.height=12, fig.width=20}
corrplot(Edif_table, is.corr = F, tl.cex = 0.7, tl.srt = 45)
```

```{r}
apply(E_table, 2, mean)[order(apply(E_table, 2, mean), decreasing = T)][1:10]
```


### 100kb 

```{r}
E_table = IBD_ldsc[,,1,3]
pE_table = IBD_ldsc[,,1,4]
qE_table = matrix(qvalue(as.vector(pE_table))$qvalues, nrow = nrow(E_table), ncol = ncol(E_table))
pE_table2 = matrix(qvalue(as.vector(pE_table))$pvalues, nrow = nrow(E_table), ncol = ncol(E_table))
E_table[which(qE_table > 0.01 & pE_table2 > 0.001)] = 1 
E_table[E_table < 1.1] = 1
Edif_table = E_table - mean(E_table)
Edif_table[Edif_table < 0] = 0
```

```{r fig.height=12, fig.width=20}
corrplot(Edif_table, is.corr = F, tl.cex = 0.7, tl.srt = 45)
```

```{r}
apply(E_table, 2, mean)[order(apply(E_table, 2, mean), decreasing = T)][1:10]
```


